package com.oliven.app;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.view.*;
import android.widget.*;
import java.text.*;
import java.util.*;

public class MainActivity extends Activity {
    static final int BG=Color.rgb(250,250,247), WHITE=Color.WHITE, TEXT=Color.rgb(24,31,26), MUTED=Color.rgb(105,113,107), GREEN=Color.rgb(47,107,70), GREEN2=Color.rgb(96,165,102), SOFT=Color.rgb(238,244,235), BORDER=Color.rgb(229,231,225), GRID=Color.rgb(234,235,231);
    LinearLayout root, content, nav; SharedPreferences prefs; ArrayList<Habit> habits=new ArrayList<>(); Calendar now=Calendar.getInstance(); int activeTab=0; String filter="Todos";
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(WHITE);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);prefs=getSharedPreferences("oliven",MODE_PRIVATE);loadHabits();root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);content=new LinearLayout(this);root.addView(content,new LinearLayout.LayoutParams(-1,0,1));nav=buildNav();root.addView(nav,new LinearLayout.LayoutParams(-1,dp(60)));setContentView(root);showHome();}
    int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+.5f);} TextView tv(String s,float sp,int c,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(c);v.setGravity(Gravity.CENTER_VERTICAL);if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;} GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;} GradientDrawable cardBg(){GradientDrawable g=bg(WHITE,18);g.setStroke(dp(1),BORDER);return g;} void m(View v,int l,int t,int r,int b){LinearLayout.LayoutParams p=(v.getLayoutParams() instanceof LinearLayout.LayoutParams)?(LinearLayout.LayoutParams)v.getLayoutParams():new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(l),dp(t),dp(r),dp(b));v.setLayoutParams(p);} Space gap(int h){Space s=new Space(this);s.setLayoutParams(new LinearLayout.LayoutParams(1,dp(h)));return s;}
    LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(13),dp(11),dp(13),dp(11));c.setBackground(cardBg());return c;}
    LinearLayout buildNav(){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.HORIZONTAL);b.setBackgroundColor(WHITE);b.setPadding(dp(8),dp(4),dp(8),dp(2));String[] n={"⌂\nHoje","↗\nProgresso","✓\nHábitos","♙\nPerfil"};for(int i=0;i<4;i++){final int x=i;TextView t=tv(n[i],10,MUTED,false);t.setGravity(Gravity.CENTER);t.setTag("nav"+i);t.setOnClickListener(v->{activeTab=x;if(x==0)showHome();else if(x==1)showEvolution();else if(x==2)showHabits();else showProfile();});b.addView(t,new LinearLayout.LayoutParams(0,-1,1));}return b;}
    void navState(int x){activeTab=x;for(int i=0;i<4;i++){TextView t=nav.findViewWithTag("nav"+i);if(t!=null){t.setTextColor(i==x?GREEN:MUTED);t.setTypeface(Typeface.DEFAULT,i==x?Typeface.BOLD:Typeface.NORMAL);}}}
    LinearLayout screen(boolean scroll){content.removeAllViews();LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(16),dp(10),dp(16),dp(12));body.setBackgroundColor(BG);if(scroll){ScrollView sc=new ScrollView(this);sc.setFillViewport(true);sc.setOverScrollMode(View.OVER_SCROLL_NEVER);sc.addView(body,new ScrollView.LayoutParams(-1,-2));content.addView(sc,new LinearLayout.LayoutParams(-1,-1));}else content.addView(body,new LinearLayout.LayoutParams(-1,-1));return body;}
    View topBar(String title,boolean back,String right){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);if(back){TextView b=tv("‹",28,TEXT,false);b.setGravity(Gravity.CENTER);b.setOnClickListener(v->showHome());row.addView(b,new LinearLayout.LayoutParams(dp(34),dp(38)));}else{TextView b=tv("☰",18,TEXT,false);b.setGravity(Gravity.CENTER);row.addView(b,new LinearLayout.LayoutParams(dp(34),dp(38)));}TextView t=tv(title,16,TEXT,true);t.setGravity(Gravity.CENTER);row.addView(t,new LinearLayout.LayoutParams(0,dp(38),1));TextView r=tv(right==null?"":right,18,TEXT,false);r.setGravity(Gravity.CENTER);row.addView(r,new LinearLayout.LayoutParams(dp(34),dp(38)));return row;}
    String datePt(){String[] d={"Domingo","Segunda-feira","Terça-feira","Quarta-feira","Quinta-feira","Sexta-feira","Sábado"};String[] mm={"janeiro","fevereiro","março","abril","maio","junho","julho","agosto","setembro","outubro","novembro","dezembro"};return d[now.get(Calendar.DAY_OF_WEEK)-1]+", "+now.get(Calendar.DAY_OF_MONTH)+" de "+mm[now.get(Calendar.MONTH)];} String key(Calendar c){return new SimpleDateFormat("yyyyMMdd",Locale.US).format(c.getTime());} boolean done(Calendar c,Habit h){return prefs.getBoolean("done_"+key(c)+"_"+h.id,false);} int completed(Calendar c){int n=0;for(int i=0;i<Math.min(5,habits.size());i++)if(done(c,habits.get(i)))n++;return n;} int percent(Calendar c){int n=Math.min(5,habits.size());return n==0?0:(int)Math.round(completed(c)*100.0/n);} int monthConsistency(){int day=now.get(Calendar.DAY_OF_MONTH),sum=0;Calendar c=(Calendar)now.clone();for(int i=1;i<=day;i++){c.set(Calendar.DAY_OF_MONTH,i);sum+=percent(c);}return day==0?0:sum/day;}

    void showHome(){navState(0);LinearLayout b=screen(true);LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView menu=tv("☰",17,TEXT,false);menu.setGravity(Gravity.CENTER);top.addView(menu,new LinearLayout.LayoutParams(dp(32),dp(32)));Space s=new Space(this);top.addView(s,new LinearLayout.LayoutParams(0,1,1));TextView bell=tv("♢",18,TEXT,false);bell.setGravity(Gravity.CENTER);top.addView(bell,new LinearLayout.LayoutParams(dp(32),dp(32)));b.addView(top);TextView h=tv("Bom dia, Jean",24,TEXT,true);b.addView(h);TextView d=tv(datePt(),12,MUTED,false);b.addView(d);b.addView(gap(3));SegmentRing ring=new SegmentRing(this);ring.progress=percent(now);ring.label="Consistência\nde hoje";b.addView(ring,new LinearLayout.LayoutParams(-1,dp(185)));LinearLayout c=card();LinearLayout ch=new LinearLayout(this);ch.setGravity(Gravity.CENTER_VERTICAL);TextView ht=tv("HOJE",12,TEXT,true);ch.addView(ht,new LinearLayout.LayoutParams(0,dp(26),1));TextView count=tv(completed(now)+" de "+Math.min(5,habits.size())+" concluídos",10,GREEN,true);count.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);ch.addView(count,new LinearLayout.LayoutParams(-2,dp(26)));ch.setOnClickListener(v->showMyDay());c.addView(ch);for(int i=0;i<Math.min(5,habits.size());i++)c.addView(habitRow(habits.get(i),now,true));b.addView(c);LinearLayout insight=card();insight.setBackground(bg(SOFT,16));LinearLayout ir=new LinearLayout(this);ir.setGravity(Gravity.CENTER_VERTICAL);TextView ic=tv("↗",17,GREEN,true);ir.addView(ic,new LinearLayout.LayoutParams(dp(28),dp(42)));LinearLayout it=new LinearLayout(this);it.setOrientation(LinearLayout.VERTICAL);it.addView(tv("Você está construindo seu ritmo",12,TEXT,true));it.addView(tv("Toque para ver os insights da Oliven",10,MUTED,false));ir.addView(it,new LinearLayout.LayoutParams(0,-2,1));insight.addView(ir);insight.setOnClickListener(v->showInsights());b.addView(insight);m(insight,0,8,0,0);ring.setOnClickListener(v->showCircle());}
    View habitRow(Habit h,Calendar day,boolean clickable){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(0,dp(3),0,dp(3));boolean ok=done(day,h);TextView dot=tv(ok?"●":"○",14,ok?GREEN:MUTED,false);dot.setGravity(Gravity.CENTER);r.addView(dot,new LinearLayout.LayoutParams(dp(28),dp(36)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.addView(tv(h.name,12,TEXT,true));tx.addView(tv(h.goal,9,MUTED,false));r.addView(tx,new LinearLayout.LayoutParams(0,dp(36),1));if(clickable)r.setOnClickListener(v->{prefs.edit().putBoolean("done_"+key(day)+"_"+h.id,!done(day,h)).apply();showHome();});return r;}

    void showCircle(){navState(0);LinearLayout b=screen(true);View tb=topBar("Círculo",true,"▣");b.addView(tb);LinearLayout mon=new LinearLayout(this);mon.setGravity(Gravity.CENTER_VERTICAL);TextView left=tv("‹",18,TEXT,false), name=tv("Agosto 2026",12,TEXT,true), right=tv("›",18,TEXT,false);left.setGravity(Gravity.CENTER);right.setGravity(Gravity.CENTER);name.setGravity(Gravity.CENTER);mon.addView(left,new LinearLayout.LayoutParams(dp(45),dp(36)));mon.addView(name,new LinearLayout.LayoutParams(0,dp(36),1));mon.addView(right,new LinearLayout.LayoutParams(dp(45),dp(36)));b.addView(mon);MonthCircle mc=new MonthCircle(this);mc.progress=monthConsistency();b.addView(mc,new LinearLayout.LayoutParams(-1,dp(300)));LinearLayout day=card();day.addView(tv("16 de agosto",12,TEXT,true));for(int i=0;i<Math.min(5,habits.size());i++)day.addView(habitRow(habits.get(i),now,false));b.addView(day);}

    void showEvolution(){navState(1);LinearLayout b=screen(true);b.addView(topBar("Evolução",false,""));LinearLayout chips=new LinearLayout(this);String[] ps={"7 dias","30 dias","90 dias","1 ano"};for(String p:ps){TextView t=tv(p,10,p.equals("30 dias")?TEXT:MUTED,p.equals("30 dias"));t.setGravity(Gravity.CENTER);t.setBackground(bg(p.equals("30 dias")?SOFT:WHITE,14));chips.addView(t,new LinearLayout.LayoutParams(0,dp(30),1));}b.addView(chips);LinearLayout c=card();c.addView(tv("Taxa de consistência",10,MUTED,false));c.addView(tv(monthConsistency()+"%",29,TEXT,true));c.addView(tv("↑ 8% vs período anterior",9,GREEN,false));Trend t=new Trend(this);c.addView(t,new LinearLayout.LayoutParams(-1,dp(130)));b.addView(c);m(c,0,8,0,0);LinearLayout res=card();res.addView(tv("Resumo",12,TEXT,true));res.addView(summary("Hoje",percent(now)+"%"));res.addView(summary("Semana",last7()+"%"));res.addView(summary("Mês",monthConsistency()+"%"));res.addView(summary("Últimos 90 dias",Math.max(0,monthConsistency()-8)+"%"));b.addView(res);m(res,0,8,0,0);LinearLayout tr=card();tr.addView(tv("Tendência",10,MUTED,false));tr.addView(tv("↑ 8%",22,GREEN,true));tr.addView(tv("Melhor que o mês anterior",10,MUTED,false));b.addView(tr);m(tr,0,8,0,0);}
    View summary(String a,String v){LinearLayout r=new LinearLayout(this);r.setPadding(0,dp(5),0,dp(5));r.addView(tv(a,10,TEXT,false),new LinearLayout.LayoutParams(0,dp(24),1));TextView x=tv(v,10,GREEN,true);x.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);r.addView(x,new LinearLayout.LayoutParams(dp(60),dp(24)));return r;}

    void showMyDay(){navState(0);LinearLayout b=screen(true);b.addView(topBar("Meu Dia",true,""));TextView hoje=tv("Hoje",13,TEXT,true);b.addView(hoje);b.addView(tv(datePt(),10,MUTED,false));b.addView(gap(7));LinearLayout list=card();for(int i=0;i<Math.min(5,habits.size());i++)list.addView(habitRow(habits.get(i),now,true));b.addView(list);}

    void showHabits(){navState(2);LinearLayout b=screen(true);LinearLayout title=new LinearLayout(this);title.setGravity(Gravity.CENTER_VERTICAL);LinearLayout tt=new LinearLayout(this);tt.setOrientation(LinearLayout.VERTICAL);tt.addView(tv("Hábitos",22,TEXT,true));tt.addView(tv("Meus hábitos",10,MUTED,false));title.addView(tt,new LinearLayout.LayoutParams(0,-2,1));TextView add=tv("+",24,TEXT,false);add.setGravity(Gravity.CENTER);add.setOnClickListener(v->addHabit());title.addView(add,new LinearLayout.LayoutParams(dp(38),dp(38)));b.addView(title);LinearLayout chips=new LinearLayout(this);String[] fs={"Todos","Corpo","Mente","Projetos","Pessoal"};for(String f:fs){TextView x=tv(f,9,f.equals(filter)?GREEN:MUTED,f.equals(filter));x.setGravity(Gravity.CENTER);x.setBackground(bg(f.equals(filter)?SOFT:WHITE,13));x.setOnClickListener(v->{filter=((TextView)v).getText().toString();showHabits();});chips.addView(x,new LinearLayout.LayoutParams(0,dp(28),1));}b.addView(chips);m(chips,0,7,0,6);for(Habit h:habits){if(!filter.equals("Todos")&&!h.category.equals(filter))continue;LinearLayout row=card();row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);TextView ico=tv(h.icon,15,GREEN,true);ico.setGravity(Gravity.CENTER);ico.setBackground(bg(SOFT,15));row.addView(ico,new LinearLayout.LayoutParams(dp(38),dp(38)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.addView(tv(h.name,12,TEXT,true));tx.addView(tv(h.goal,9,MUTED,false));row.addView(tx,new LinearLayout.LayoutParams(0,-2,1));m(tx,10,0,0,0);TextView menu=tv("⋮",18,MUTED,false);menu.setGravity(Gravity.CENTER);row.addView(menu,new LinearLayout.LayoutParams(dp(30),dp(38)));b.addView(row);m(row,0,4,0,0);}}
    void addHabit(){LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);f.setPadding(dp(16),0,dp(16),0);EditText n=new EditText(this);n.setHint("Nome do hábito");EditText g=new EditText(this);g.setHint("Meta");f.addView(n);f.addView(g);new AlertDialog.Builder(this).setTitle("Novo hábito").setView(f).setNegativeButton("Cancelar",null).setPositiveButton("Adicionar",(d,w)->{String a=n.getText().toString().trim(),z=g.getText().toString().trim();if(a.length()>0){habits.add(new Habit(System.currentTimeMillis(),a,z.length()==0?"Diário":z,"Pessoal","✓"));saveHabits();showHabits();}}).show();}

    void showCalendar(){navState(1);LinearLayout b=screen(true);b.addView(topBar("Calendário",true,""));LinearLayout c=card();LinearLayout mh=new LinearLayout(this);mh.setGravity(Gravity.CENTER_VERTICAL);TextView l=tv("‹",18,TEXT,false),mt=tv("Agosto 2026",12,TEXT,true),r=tv("›",18,TEXT,false);mt.setGravity(Gravity.CENTER);l.setGravity(Gravity.CENTER);r.setGravity(Gravity.CENTER);mh.addView(l,new LinearLayout.LayoutParams(dp(40),dp(32)));mh.addView(mt,new LinearLayout.LayoutParams(0,dp(32),1));mh.addView(r,new LinearLayout.LayoutParams(dp(40),dp(32)));c.addView(mh);c.addView(calendarGrid());b.addView(c);LinearLayout foot=card();foot.setOrientation(LinearLayout.HORIZONTAL);foot.addView(tv(monthConsistency()+"%  Consistência do mês",12,GREEN,true),new LinearLayout.LayoutParams(0,dp(34),1));TextView x=tv("25 dias concluídos",9,MUTED,false);x.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);foot.addView(x,new LinearLayout.LayoutParams(-2,dp(34)));b.addView(foot);m(foot,0,8,0,0);}
    View calendarGrid(){GridLayout g=new GridLayout(this);g.setColumnCount(7);String[] w={"D","S","T","Q","Q","S","S"};for(String a:w){TextView x=tv(a,9,MUTED,false);x.setGravity(Gravity.CENTER);g.addView(x);cell(x,28);}Calendar f=(Calendar)now.clone();f.set(Calendar.DAY_OF_MONTH,1);for(int i=0;i<f.get(Calendar.DAY_OF_WEEK)-1;i++){TextView x=tv("",9,MUTED,false);g.addView(x);cell(x,28);}for(int d=1;d<=31;d++){TextView x=tv(String.valueOf(d),9,d==16?GREEN:TEXT,d==16);x.setGravity(Gravity.CENTER);if(d==16)x.setBackground(bg(SOFT,20));g.addView(x);cell(x,32);}return g;} void cell(View v,int h){GridLayout.LayoutParams p=new GridLayout.LayoutParams();p.width=0;p.height=dp(h);p.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);v.setLayoutParams(p);}

    void showInsights(){navState(1);LinearLayout b=screen(true);b.addView(topBar("Insights da Oliven",true,""));String[][] ins={{"↗","Você é mais consistente\nnas segundas e terças.","Taxa média nesses dias: 87%"},{"◷","Suas noites após as 21h\ntêm menor conclusão.","Considere ajustar sua rotina."},{"↗","Seu desempenho geral\nmelhorou 8% este mês.","Continue evoluindo!"}};for(String[] z:ins){LinearLayout c=card();c.setOrientation(LinearLayout.HORIZONTAL);TextView ic=tv(z[0],20,GREEN,false);ic.setGravity(Gravity.CENTER);c.addView(ic,new LinearLayout.LayoutParams(dp(48),dp(62)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.addView(tv(z[1],11,TEXT,true));tx.addView(tv(z[2],9,MUTED,false));c.addView(tx,new LinearLayout.LayoutParams(0,-2,1));b.addView(c);m(c,0,7,0,0);}LinearLayout more=card();more.addView(tv("Ver todos os insights    ›",10,TEXT,false));b.addView(more);m(more,0,8,0,0);}

    void showYear(){navState(1);LinearLayout b=screen(true);b.addView(topBar("Meu ano",true,""));LinearLayout hdr=new LinearLayout(this);hdr.setGravity(Gravity.CENTER_VERTICAL);hdr.addView(tv("‹",18,TEXT,false),new LinearLayout.LayoutParams(dp(40),dp(32)));TextView t=tv("Meu ano em 2026",12,TEXT,true);t.setGravity(Gravity.CENTER);hdr.addView(t,new LinearLayout.LayoutParams(0,dp(32),1));TextView rr=tv("›",18,TEXT,false);rr.setGravity(Gravity.CENTER);hdr.addView(rr,new LinearLayout.LayoutParams(dp(40),dp(32)));b.addView(hdr);GridLayout g=new GridLayout(this);g.setColumnCount(4);String[] ms={"JAN","FEV","MAR","ABR","MAI","JUN","JUL","AGO","SET","OUT","NOV","DEZ"};int[] pv={92,81,76,88,73,84,79,82,0,0,0,0};for(int i=0;i<12;i++){LinearLayout cc=new LinearLayout(this);cc.setOrientation(LinearLayout.VERTICAL);cc.setGravity(Gravity.CENTER);cc.addView(tv(ms[i],9,TEXT,true));SmallRing sr=new SmallRing(this);sr.p=pv[i];cc.addView(sr,new LinearLayout.LayoutParams(dp(70),dp(70)));g.addView(cc);GridLayout.LayoutParams gp=new GridLayout.LayoutParams();gp.width=0;gp.height=dp(95);gp.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);cc.setLayoutParams(gp);}b.addView(g);}

    void showProfile(){navState(3);LinearLayout b=screen(true);b.addView(topBar("Perfil",false,""));LinearLayout u=card();u.setOrientation(LinearLayout.HORIZONTAL);u.setGravity(Gravity.CENTER_VERTICAL);TextView av=tv("J",20,WHITE,true);av.setGravity(Gravity.CENTER);av.setBackground(bg(GREEN,34));u.addView(av,new LinearLayout.LayoutParams(dp(54),dp(54)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.addView(tv("Jean Silva",12,TEXT,true));tx.addView(tv("Membro desde abr/2024",8,MUTED,false));u.addView(tx,new LinearLayout.LayoutParams(0,-2,1));m(tx,12,0,0,0);b.addView(u);String[][] s={{"Dados pessoais","Nome, preferências e objetivo"},{"Preferências","Aparência e rotina"},{"Notificações","Lembretes da rotina"},{"Backup e sincronização","Em breve"},{"Ajuda e suporte","Central de ajuda"},{"Sobre a Oliven","Oliven 1.0.4 • Android nativo"}};for(String[] x:s){LinearLayout c=card();c.setOrientation(LinearLayout.HORIZONTAL);LinearLayout z=new LinearLayout(this);z.setOrientation(LinearLayout.VERTICAL);z.addView(tv(x[0],11,TEXT,true));z.addView(tv(x[1],8,MUTED,false));c.addView(z,new LinearLayout.LayoutParams(0,-2,1));TextView ar=tv("›",18,MUTED,false);ar.setGravity(Gravity.CENTER);c.addView(ar,new LinearLayout.LayoutParams(dp(28),dp(34)));b.addView(c);m(c,0,5,0,0);}}

    int last7(){int s=0;Calendar c=(Calendar)now.clone();for(int i=0;i<7;i++){s+=percent(c);c.add(Calendar.DAY_OF_MONTH,-1);}return s/7;} void loadHabits(){String raw=prefs.getString("habits_v104",null);if(raw==null){habits.add(new Habit(1,"Academia","5x por semana","Corpo","◉"));habits.add(new Habit(2,"Projeto Homem de Ferro","1h42 / 2h","Projetos","◆"));habits.add(new Habit(3,"Beber água","3,2 / 3 litros","Corpo","●"));habits.add(new Habit(4,"Leitura","30 min por dia","Mente","▤"));habits.add(new Habit(5,"Organização","Concluída","Pessoal","✓"));habits.add(new Habit(6,"Cardio","4x por semana","Corpo","♥"));habits.add(new Habit(7,"Estudo","1h por dia","Mente","▤"));return;}for(String ln:raw.split("\\n")){String[] p=ln.split("\\|",-1);if(p.length>=5)try{habits.add(new Habit(Long.parseLong(p[0]),p[1],p[2],p[3],p[4]));}catch(Exception ignored){}}} void saveHabits(){StringBuilder s=new StringBuilder();for(Habit h:habits)s.append(h.id).append('|').append(h.name.replace("|","")).append('|').append(h.goal.replace("|","")).append('|').append(h.category).append('|').append(h.icon).append('\n');prefs.edit().putString("habits_v104",s.toString()).apply();} static class Habit{long id;String name,goal,category,icon;Habit(long i,String n,String g,String c,String x){id=i;name=n;goal=g;category=c;icon=x;}}

    class SegmentRing extends View{Paint p=new Paint(1);int progress;String label="";SegmentRing(Context c){super(c);}protected void onDraw(Canvas c){float cx=getWidth()/2f,cy=getHeight()/2f,r=Math.min(getWidth(),getHeight())*.36f;p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(7));p.setStrokeCap(Paint.Cap.BUTT);for(int i=0;i<60;i++){p.setColor(i<Math.round(progress*.6f)?GREEN:Color.rgb(232,235,230));c.drawArc(cx-r,cy-r,cx+r,cy+r,-90+i*6,4,false,p);}p.setStyle(Paint.Style.FILL);p.setTextAlign(Paint.Align.CENTER);p.setColor(TEXT);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(dp(33));c.drawText(progress+"%",cx,cy+dp(5),p);p.setTypeface(Typeface.DEFAULT);p.setTextSize(dp(10));p.setColor(MUTED);c.drawText("Consistência",cx,cy+dp(22),p);c.drawText("de hoje",cx,cy+dp(34),p);}}
    class MonthCircle extends View{Paint p=new Paint(1);int progress;MonthCircle(Context c){super(c);}protected void onDraw(Canvas c){float cx=getWidth()/2f,cy=getHeight()/2f,r=Math.min(getWidth(),getHeight())*.35f;p.setStrokeWidth(dp(9));p.setStyle(Paint.Style.STROKE);for(int i=0;i<31;i++){p.setColor(i<16?(i%4==0?GREEN:GREEN2):Color.rgb(229,232,227));c.drawArc(cx-r,cy-r,cx+r,cy+r,-90+i*(360f/31f),7,false,p);}p.setStyle(Paint.Style.FILL);p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.DEFAULT_BOLD);p.setColor(TEXT);p.setTextSize(dp(38));c.drawText("16",cx,cy-dp(3),p);p.setTextSize(dp(9));p.setTypeface(Typeface.DEFAULT);c.drawText("AGO",cx,cy+dp(14),p);c.drawText("Domingo",cx,cy+dp(28),p);}}
    class Trend extends View{Paint p=new Paint(1);Trend(Context c){super(c);}protected void onDraw(Canvas c){float w=getWidth(),h=getHeight();p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(1));p.setColor(GRID);for(int i=1;i<4;i++)c.drawLine(0,h*i/4,w,h*i/4,p);float[] y={.72f,.58f,.47f,.35f,.43f,.29f,.33f,.18f,.21f,.08f};Path q=new Path();p.setColor(GREEN);p.setStrokeWidth(dp(2));for(int i=0;i<y.length;i++){float x=w*i/(y.length-1),yy=h*y[i];if(i==0)q.moveTo(x,yy);else q.lineTo(x,yy);}c.drawPath(q,p);}}
    class SmallRing extends View{Paint pnt=new Paint(1);int p;SmallRing(Context c){super(c);}protected void onDraw(Canvas c){float x=getWidth()/2f,y=getHeight()/2f,r=Math.min(x,y)-dp(8);pnt.setStyle(Paint.Style.STROKE);pnt.setStrokeWidth(dp(3));pnt.setColor(Color.rgb(226,230,224));c.drawCircle(x,y,r,pnt);if(p>0){pnt.setColor(GREEN2);c.drawArc(x-r,y-r,x+r,y+r,-90,p*3.6f,false,pnt);}pnt.setStyle(Paint.Style.FILL);pnt.setTextAlign(Paint.Align.CENTER);pnt.setTypeface(Typeface.DEFAULT_BOLD);pnt.setTextSize(dp(9));pnt.setColor(TEXT);c.drawText(p==0?"–":p+"%",x,y+dp(3),pnt);}}
}
