package com.oliven.app;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import android.view.*;
import android.widget.*;
import java.text.*;
import java.util.*;

public class MainActivity extends Activity {
    private OlivenView view;
    @Override public void onCreate(Bundle b){
        super.onCreate(b);
        getWindow().setStatusBarColor(Color.rgb(249,250,247));
        getWindow().setNavigationBarColor(Color.WHITE);
        getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);
        view=new OlivenView(this); setContentView(view);
    }

    class OlivenView extends View {
        final int BG=Color.rgb(249,250,247), WHITE=Color.WHITE, TEXT=Color.rgb(20,26,21), MUTED=Color.rgb(100,108,101), GREEN=Color.rgb(30,101,67), SOFT=Color.rgb(239,245,236), BORDER=Color.rgb(224,228,220), LIGHT=Color.rgb(232,237,229);
        Paint p=new Paint(3); float s=1f,H=800; int screen=0; SharedPreferences prefs; ArrayList<Habit> habits=new ArrayList<>(); RectF menuHit=new RectF(), ringHit=new RectF(), todayHit=new RectF(), insightHit=new RectF(); Calendar now=Calendar.getInstance();
        String[] nav={"Hoje","Progresso","Hábitos","Perfil"};
        OlivenView(Context c){super(c);prefs=getSharedPreferences("oliven",MODE_PRIVATE);load();}
        void load(){habits.add(new Habit(1,"Academia","5x por semana","Corpo"));habits.add(new Habit(2,"Projeto Homem de Ferro","1h42 / 2h","Projetos"));habits.add(new Habit(3,"Beber água","3,2 / 3 litros","Corpo"));habits.add(new Habit(4,"Leitura","30 min por dia","Mente"));habits.add(new Habit(5,"Organização","Concluída","Pessoal"));habits.add(new Habit(6,"Cardio","4x por semana","Corpo"));habits.add(new Habit(7,"Estudo","1h por dia","Mente"));}
        String key(int id){return "done_"+new SimpleDateFormat("yyyyMMdd",Locale.US).format(now.getTime())+"_"+id;} int done(){int n=0;for(int i=0;i<5;i++)if(prefs.getBoolean(key(habits.get(i).id),false))n++;return n;} int pct(){return done()*20;} int monthPct(){return Math.max(0,(pct()+80)/17);} float X(float v){return v*s;} float Y(float v){return v*s;}
        @Override protected void onDraw(Canvas c){super.onDraw(c);s=getWidth()/390f;H=getHeight()/s;c.drawColor(BG);if(screen==0)home(c);else if(screen==1)evolution(c);else if(screen==2)habits(c);else if(screen==3)profile(c);else if(screen==4)circle(c);else if(screen==5)myday(c);else if(screen==6)calendar(c);else if(screen==7)insights(c);else year(c);bottom(c);}
        void font(float z,int color,boolean bold){p.setTypeface(bold?Typeface.create("sans",Typeface.BOLD):Typeface.create("sans",Typeface.NORMAL));p.setTextSize(X(z));p.setColor(color);p.setStyle(Paint.Style.FILL);} void text(Canvas c,String t,float x,float y,float z,int color,boolean bold){font(z,color,bold);p.setTextAlign(Paint.Align.LEFT);c.drawText(t,X(x),Y(y),p);} void centered(Canvas c,String t,float x,float y,float z,int color,boolean bold){font(z,color,bold);p.setTextAlign(Paint.Align.CENTER);c.drawText(t,X(x),Y(y),p);p.setTextAlign(Paint.Align.LEFT);} void round(Canvas c,float l,float t,float r,float b,float rad,int color){p.setColor(color);p.setStyle(Paint.Style.FILL);c.drawRoundRect(X(l),Y(t),X(r),Y(b),X(rad),X(rad),p);} void card(Canvas c,float l,float t,float r,float b,float rad){round(c,l,t,r,b,rad,WHITE);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(X(.8f));p.setColor(BORDER);c.drawRoundRect(X(l),Y(t),X(r),Y(b),X(rad),X(rad),p);} void line(Canvas c,float x1,float y1,float x2,float y2,int color,float w){p.setColor(color);p.setStrokeWidth(X(w));p.setStyle(Paint.Style.STROKE);c.drawLine(X(x1),Y(y1),X(x2),Y(y2),p);}
        void hamburger(Canvas c,float x,float y){for(int i=0;i<3;i++)line(c,x,y+i*5,x+14,y+i*5,TEXT,1.2f);menuHit.set(X(x-10),Y(y-14),X(x+30),Y(y+26));} void bell(Canvas c,float x,float y){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(X(1.1f));p.setColor(TEXT);RectF r=new RectF(X(x-5),Y(y-7),X(x+5),Y(y+7));c.drawArc(r,200,140,false,p);line(c,x-6,y+4,x+6,y+4,TEXT,1.1f);line(c,x,y+5,x,y+8,TEXT,1.1f);} String date(){return "Domingo, 16 de agosto";}
        void segmentedRing(Canvas c,float cx,float cy,float r,int progress){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(X(6));p.setStrokeCap(Paint.Cap.BUTT);int fill=Math.round(progress*.6f);for(int i=0;i<60;i++){p.setColor(i<fill?Color.rgb(86,163,79):LIGHT);RectF rr=new RectF(X(cx-r),Y(cy-r),X(cx+r),Y(cy+r));c.drawArc(rr,-90+i*6,4,false,p);}p.setStrokeCap(Paint.Cap.ROUND);} void topMenu(Canvas c,String title,boolean center){hamburger(c,24,27);if(center)centered(c,title,195,36,17,TEXT,true);else text(c,title,20,46,25,TEXT,true);}
        void home(Canvas c){hamburger(c,24,27);bell(c,358,28);text(c,"Bom dia, Jean",20,67,21,TEXT,true);text(c,date(),20,83,11,MUTED,false);segmentedRing(c,195,163,57,pct());centered(c,pct()+"%",195,165,31,TEXT,true);centered(c,"Consistência",195,181,9,MUTED,false);centered(c,"de hoje",195,192,9,MUTED,false);ringHit.set(X(130),Y(96),X(260),Y(225));card(c,18,228,372,456,18);text(c,"HOJE",30,253,12,TEXT,true);text(c,done()+" de 5 concluídos",281,253,11,GREEN,true);String[] names={"Academia","Projeto Homem de Ferro","Beber água","Leitura","Organização"};String[] sub={"5x por semana","1h42 / 2h","3,2 / 3 litros","30 min por dia","Concluída"};for(int i=0;i<5;i++){float yy=282+i*34;boolean d=prefs.getBoolean(key(habits.get(i).id),false);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(X(1));p.setColor(d?GREEN:MUTED);c.drawCircle(X(42),Y(yy-5),X(5),p);if(d){p.setStyle(Paint.Style.FILL);p.setColor(GREEN);c.drawCircle(X(42),Y(yy-5),X(4),p);}text(c,names[i],55,yy-8,12,TEXT,true);text(c,sub[i],55,yy+5,9,MUTED,false);}todayHit.set(X(18),Y(228),X(372),Y(456));round(c,18,464,372,522,17,SOFT);text(c,"↗",30,496,15,GREEN,true);text(c,"Você está construindo seu ritmo",55,488,12,TEXT,true);text(c,"Toque para ver os insights da Oliven",55,504,9,MUTED,false);insightHit.set(X(18),Y(464),X(372),Y(522));}
        void evolution(Canvas c){topMenu(c,"Evolução",true);String[] chips={"7 dias","30 dias","90 dias","1 ano"};for(int i=0;i<4;i++){float l=18+i*89;round(c,l,48,l+85,76,15,i==1?SOFT:WHITE);centered(c,chips[i],l+42.5f,67,9,i==1?TEXT:MUTED,i==1);}card(c,18,84,372,276,16);text(c,"Taxa de consistência",30,106,10,MUTED,false);text(c,monthPct()+"%",30,139,26,TEXT,true);text(c,"↑ 8% vs período anterior",30,156,9,GREEN,false);for(int i=1;i<=3;i++)line(c,30,170+i*23,360,170+i*23,BORDER,.7f);float[] yy={245,228,211,196,205,190,196,174,178,158};p.setColor(GREEN);p.setStrokeWidth(X(1.8f));p.setStyle(Paint.Style.STROKE);Path path=new Path();for(int i=0;i<yy.length;i++){float xx=30+i*36.5f;if(i==0)path.moveTo(X(xx),Y(yy[i]));else path.lineTo(X(xx),Y(yy[i]));}c.drawPath(path,p);card(c,18,285,372,438,16);text(c,"Resumo",30,309,12,TEXT,true);String[] a={"Hoje","Semana","Mês","Últimos 90 dias"};int[] v={pct(),Math.max(0,pct()/2),monthPct(),Math.max(0,monthPct()-8)};for(int i=0;i<4;i++){text(c,a[i],30,333+i*28,10,TEXT,false);text(c,v[i]+"%",340,333+i*28,10,GREEN,true);}card(c,18,448,372,520,16);text(c,"Tendência",30,469,10,MUTED,false);text(c,"↑ 8%",30,494,21,GREEN,true);text(c,"Melhor que o mês anterior",30,510,9,MUTED,false);}
        void habits(Canvas c){text(c,"Hábitos",18,44,25,TEXT,true);text(c,"Meus hábitos",18,62,10,MUTED,false);text(c,"+",350,47,25,TEXT,true);String[] cats={"Todos","Corpo","Mente","Projetos","Pessoal"};for(int i=0;i<5;i++){float l=18+i*70;round(c,l,72,l+66,98,14,i==0?SOFT:WHITE);centered(c,cats[i],l+33,90,8,i==0?GREEN:MUTED,i==0);}String[] icons={"◉","◆","●","▤","✓","♥","▤"};for(int i=0;i<7;i++){float t=108+i*58;card(c,18,t,372,t+52,15);round(c,30,t+9,64,t+43,12,SOFT);centered(c,icons[i],47,t+31,12,i==5?Color.rgb(230,45,62):GREEN,true);text(c,habits.get(i).name,76,t+25,12,TEXT,true);text(c,habits.get(i).goal,76,t+39,9,MUTED,false);text(c,"⋮",344,t+32,17,MUTED,false);}}
        void profile(Canvas c){topMenu(c,"Perfil",true);card(c,18,48,372,114,16);p.setColor(GREEN);p.setStyle(Paint.Style.FILL);c.drawCircle(X(55),Y(81),X(24),p);centered(c,"J",55,88,20,WHITE,true);text(c,"Jean Silva",92,78,13,TEXT,true);text(c,"Membro desde abr/2024",92,91,8,MUTED,false);String[][] rows={{"Dados pessoais","Nome, preferências e objetivo"},{"Preferências","Aparência e rotina"},{"Notificações","Lembretes da rotina"},{"Backup e sincronização","Em breve"},{"Ajuda e suporte","Central de ajuda"},{"Sobre a Oliven","Oliven 1.0.5 · Android nativo"}};for(int i=0;i<6;i++){float t=122+i*56;card(c,18,t,372,t+49,14);text(c,rows[i][0],30,t+23,11,TEXT,true);text(c,rows[i][1],30,t+36,8,MUTED,false);text(c,"›",344,t+31,18,MUTED,false);}}
        void circle(Canvas c){text(c,"‹",18,39,21,TEXT,false);centered(c,"Círculo",195,38,16,TEXT,true);text(c,"▣",350,38,14,TEXT,false);text(c,"‹",25,70,18,TEXT,false);centered(c,"Agosto 2026",195,68,11,TEXT,true);text(c,"›",355,70,18,TEXT,false);float cx=195,cy=196,r=84;for(int i=0;i<31;i++){double a=Math.toRadians(-90+i*(360.0/31));float x=(float)(cx+Math.cos(a)*r),y=(float)(cy+Math.sin(a)*r);p.setColor(i<16?Color.rgb(126,194,113):LIGHT);p.setStyle(Paint.Style.FILL);c.drawRect(X(x-5),Y(y-9),X(x+5),Y(y+9),p);if(i%2==0){float tx=(float)(cx+Math.cos(a)*(r+18)),ty=(float)(cy+Math.sin(a)*(r+18));centered(c,String.valueOf(i+1),tx,ty+3,7,MUTED,false);}}p.setColor(WHITE);p.setStyle(Paint.Style.FILL);c.drawCircle(X(cx),Y(cy),X(52),p);centered(c,"16",cx,cy-2,28,TEXT,true);centered(c,"AGO",cx,cy+15,8,MUTED,true);centered(c,"Domingo",cx,cy+28,8,TEXT,false);card(c,18,310,372,520,14);text(c,"16 de agosto",30,334,11,TEXT,true);for(int i=0;i<5;i++){float yy=365+i*29;text(c,habits.get(i).name,55,yy,10,TEXT,true);text(c,habits.get(i).goal,55,yy+11,8,MUTED,false);p.setStyle(Paint.Style.STROKE);p.setColor(i==1||i==2||i==4?GREEN:MUTED);p.setStrokeWidth(X(1));c.drawCircle(X(35),Y(yy-4),X(5),p);}}
        void myday(Canvas c){text(c,"‹",18,39,21,TEXT,false);centered(c,"Meu Dia",195,38,16,TEXT,true);text(c,"Hoje",24,72,18,TEXT,true);text(c,date(),24,90,9,MUTED,false);text(c,"3 de 5 concluídos",288,72,9,GREEN,true);card(c,18,108,372,405,16);for(int i=0;i<5;i++){float yy=143+i*51;p.setStyle(Paint.Style.STROKE);p.setColor(i==1||i==2||i==4?GREEN:MUTED);p.setStrokeWidth(X(1));c.drawCircle(X(38),Y(yy),X(6),p);if(i==1||i==2||i==4){p.setStyle(Paint.Style.FILL);p.setColor(GREEN);c.drawCircle(X(38),Y(yy),X(5),p);}text(c,habits.get(i).name,58,yy-4,12,TEXT,true);text(c,habits.get(i).goal,58,yy+11,8,MUTED,false);}}
        void calendar(Canvas c){text(c,"‹",18,39,21,TEXT,false);centered(c,"Calendário",195,38,16,TEXT,true);text(c,"‹",28,72,18,TEXT,false);centered(c,"Agosto 2026",195,70,10,TEXT,true);text(c,"›",350,72,18,TEXT,false);String[] wk={"D","S","T","Q","Q","S","S"};for(int i=0;i<7;i++)centered(c,wk[i],52+i*48,103,8,MUTED,false);int day=1;for(int row=0;row<5;row++)for(int col=0;col<7;col++){if(row==0&&col<6)continue;if(day>31)continue;float x=52+col*48,y=132+row*44;if(day==16)round(c,x-13,y-16,x+13,y+10,13,Color.rgb(79,155,67));else if(day<16)round(c,x-11,y-14,x+11,y+8,12,SOFT);centered(c,String.valueOf(day),x,y,9,day==16?WHITE:(day<16?GREEN:MUTED),day==16);day++;}card(c,18,374,372,427,14);text(c,monthPct()+"%",30,406,21,GREEN,true);text(c,"Consistência do mês",80,403,9,MUTED,false);text(c,"25 dias concluídos",275,403,9,TEXT,false);}
        void insights(Canvas c){text(c,"‹",18,39,21,TEXT,false);centered(c,"Insights da Oliven",195,38,16,TEXT,true);String[][] rows={{"↗","Você é mais consistente","nas segundas e terças.","Taxa média nesses dias: 87%"},{"◷","Suas noites após as 21h","têm menor conclusão.","Considere ajustar sua rotina."},{"↗","Seu desempenho geral","melhorou 8% este mês.","Continue evoluindo!"}};for(int i=0;i<3;i++){float t=64+i*120;card(c,18,t,372,t+104,16);text(c,rows[i][0],34,t+40,19,GREEN,true);text(c,rows[i][1],72,t+29,12,TEXT,true);text(c,rows[i][2],72,t+45,10,TEXT,true);text(c,rows[i][3],72,t+66,9,MUTED,false);}card(c,18,438,372,486,12);text(c,"Ver todos os insights",30,467,10,TEXT,false);text(c,"›",344,467,18,MUTED,false);}
        void year(Canvas c){text(c,"‹",18,39,21,TEXT,false);centered(c,"Meu ano em 2026",195,38,16,TEXT,true);text(c,"›",350,39,21,TEXT,false);String[] m={"JAN","FEV","MAR","ABR","MAI","JUN","JUL","AGO","SET","OUT","NOV","DEZ"};int[] vals={92,81,76,88,73,84,79,82,0,0,0,0};for(int i=0;i<12;i++){int col=i%4,row=i/4;float cx=61+col*89,cy=105+row*105;centered(c,m[i],cx,cy-28,8,MUTED,true);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(X(2.2f));p.setColor(vals[i]>0?GREEN:BORDER);c.drawCircle(X(cx),Y(cy),X(24),p);centered(c,vals[i]>0?vals[i]+"%":"–",cx,cy+4,9,vals[i]>0?TEXT:MUTED,true);}}
        void bottom(Canvas c){float y=H-58;round(c,0,y,390,H,0,WHITE);int active=(screen==0||screen>=4)?0:(screen==1?1:(screen==2?2:3));float[] xs={54,146,242,336};String[] ic={"⌂","↗","✓","♙"};for(int i=0;i<4;i++){centered(c,ic[i],xs[i],y+22,14,i==active?GREEN:MUTED,false);centered(c,nav[i],xs[i],y+42,9,i==active?GREEN:MUTED,i==active);}}
        void showMenu(){final String[] items={"Tela Inicial","Círculo","Evolução","Meu Dia","Hábitos","Calendário","Insights da Oliven","Meu Ano","Perfil"};new AlertDialog.Builder(MainActivity.this).setTitle("Oliven").setItems(items,(d,w)->{screen=new int[]{0,4,1,5,2,6,7,8,3}[w];invalidate();}).show();}
        @Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_UP)return true;float x=e.getX()/s,y=e.getY()/s;if(menuHit.contains(e.getX(),e.getY())){showMenu();return true;}if(y>H-65){if(x<100)screen=0;else if(x<195)screen=1;else if(x<290)screen=2;else screen=3;invalidate();return true;}if(screen==0){if(ringHit.contains(e.getX(),e.getY()))screen=4;else if(todayHit.contains(e.getX(),e.getY()))screen=5;else if(insightHit.contains(e.getX(),e.getY()))screen=7;invalidate();return true;}if(screen==2&&x>330&&y<70){newHabit();return true;}if(screen>=4&&y<55&&x<55){screen=0;invalidate();return true;}return true;}
        void newHabit(){LinearLayout box=new LinearLayout(MainActivity.this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(40,0,40,0);EditText n=new EditText(MainActivity.this);n.setHint("Nome do hábito");EditText g=new EditText(MainActivity.this);g.setHint("Meta");box.addView(n);box.addView(g);new AlertDialog.Builder(MainActivity.this).setTitle("Novo hábito").setView(box).setNegativeButton("Cancelar",null).setPositiveButton("Adicionar",(d,w)->{}).show();}
        class Habit{int id;String name,goal,cat;Habit(int i,String n,String g,String c){id=i;name=n;goal=g;cat=c;}}
    }
}
